#!/bin/bash

git_push() {
    git pull --strategy=merge > /dev/null 2>&1
    
    DATE=$(date +"%Y-%m-%d")
    TIME=$(date +"%H:%M:%S")
    
    FILES=$(git status --porcelain | awk '{print $2}' | paste -sd "," -)
    
    if [ $# -gt 0 ]; then
        MESSAGE="$DATE $TIME: $* | Files: $FILES"
    else
        MESSAGE="$DATE $TIME | Files: $FILES"
    fi
    
    git add * > /dev/null 2>&1
    git commit -m "$MESSAGE" > /dev/null 2>&1
    git push > /dev/null 2>&1
}


