#!/bin/bash
nohup git pull --strategy=merge > /dev/null 2>&1
DATE=$(date +"%Y-%m-%d")
TIME=$(date +"%H:%M:%S")
if [ $# -gt 0 ]; then
  MESSAGE="$DATE $TIME: $*"
else
  MESSAGE="$DATE $TIME"
fi
nohup git add * > /dev/null 2>&1
nohup git commit -m "$MESSAGE" > /dev/null 2>&1
nohup git push  > /dev/null 2>&1
